server:
  port: 8080

spring:
  application:
    name: web-spider
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz90vvwo94auohm728o.mysql.rds.aliyuncs.com:3306/test?serverTimezone=UTC&characterEncoding=utf8mb4&useUnicode=true&useSSL=false
    username: root
    password: root

  jpa:
    # 配置DBMS类型
    database: MYSQL
    # 配置是否将执行的SQL输出到日志
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
